# Generated by Django 6.0.3 on 2026-04-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('concert', 'Concert'), ('party', 'Party'), ('other', 'Other')], default='other', max_length=50)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('external_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
